import { Recipe } from '../models/recipe';

const recipe: Recipe = {
	id: "678faa83eb0ee52686998935" ,
	name: "Saucy Moroccan-Spiced Lentils",
	img: "https://minimalistbaker.com/wp-content/uploads/2017/11/Moroccan-Lentils-SQUARE.jpg",
	ingredients: [
		{
			amount: "2",
			unit: "cups",
			name: "water",
			notes: "",
			converted: { amount: "480", unit: "ml" },
			id: "678faa83eb0ee52686998936",
		},
		{
			amount: "1",
			unit: "cup",
			name: "green lentils",
			notes: "(rinsed and well drained // or sub canned lentils lightly rinsed and well drained)",
			converted: { amount: "192", unit: "g" },
			id: "678faa83eb0ee52686998937",
		},
		{
			amount: "3",
			unit: "cloves",
			name: "garlic*",
			notes: "(skins removed)",
			converted: { amount: "9", unit: "g" },
			id: "678faa83eb0ee52686998938",
		},
		{
			amount: "1/2",
			unit: "medium",
			name: "onion",
			notes: "(or 2 small shallots // chopped)",
			converted: { amount: "55", unit: "g" },
			id: "678faa83eb0ee52686998939",
		},
		{
			amount: "1",
			unit: "large",
			name: "red bell pepper",
			notes: "(or use 2 small), seeds removed, roughly chopped",
			converted: { amount: "150", unit: "g" },
			id: "678faa83eb0ee5268699893a",
		},
		{
			amount: "2",
			unit: "Tbsp",
			name: "tomato paste",
			notes: "",
			converted: { amount: "30", unit: "g" },
			id: "678faa83eb0ee5268699893b",
		},
		{
			amount: "1 1/2",
			unit: "Tbsp",
			name: "coconut sugar or maple syrup",
			notes: "(or stevia to taste)",
			converted: { amount: "18", unit: "g" },
			id: "678faa83eb0ee5268699893c",
		},
		{
			amount: "1/2",
			unit: "tsp",
			name: "sea salt",
			notes: "(plus more to taste)",
			converted: { amount: "1/2", unit: "tsp" },
			id: "678faa83eb0ee5268699893d",
		},
		{
			amount: "1",
			unit: "Tbsp",
			name: "smoked or sweet paprika",
			notes: "(plus more to taste)",
			converted: { amount: "7", unit: "g" },
			id: "678faa83eb0ee5268699893e",
		},
		{
			amount: "1",
			unit: "tsp",
			name: "ground cumin",
			notes: "(plus more to taste)",
			converted: { amount: "1", unit: "tsp" },
			id: "678faa83eb0ee5268699893f",
		},
		{
			amount: "1/2",
			unit: "tsp",
			name: "ground coriander",
			notes: "(plus more to taste)",
			converted: { amount: "1/2", unit: "tsp" },
			id: "678faa83eb0ee52686998940",
		},
		{
			amount: "1",
			unit: "tsp",
			name: "ground ginger",
			notes: "(plus more to taste)",
			converted: { amount: "1", unit: "tsp" },
			id: "678faa83eb0ee52686998941",
		},
		{
			amount: "1/2",
			unit: "tsp",
			name: "ground turmeric",
			notes: "(plus more to taste)",
			converted: { amount: "1/2", unit: "tsp" },
			id: "678faa83eb0ee52686998942",
		},
		{
			amount: "1/2",
			unit: "tsp",
			name: "cayenne pepper",
			notes: "(more or less to preferred spice level)",
			converted: { amount: "1/2", unit: "tsp" },
			id: "678faa83eb0ee52686998943",
		},
		{
			amount: "1 1/2",
			unit: "Tbsp",
			name: "apple cider vinegar",
			notes: "(or lemon juice)",
			converted: { amount: "22", unit: "ml" },
			id: "678faa83eb0ee52686998944",
		},
		{
			amount: "3/4",
			unit: "cup",
			name: "fresh chopped parsley or cilantro",
			notes: "(I used 1/2 cilantro + 1/2 parsley)",
			converted: { amount: "~22", unit: "g" },
			id: "678faa83eb0ee52686998945",
		},
	],
	instructions: [
		"Cook lentils first by bringing water to a boil and adding lentils. Bring back to a boil. Then reduce heat to low and simmer (uncovered) for about 20 minutes or until lentils are tender.",
		"In the meantime, to a food processor or small blender, add garlic*, onion or shallot*, bell pepper, tomato paste, coconut sugar, sea salt, paprika, cumin, coriander, ginger, turmeric, cayenne pepper, and apple cider vinegar. Mix to thoroughly combine.",
		"Taste and adjust flavor as needed, adding more tomato paste for depth of flavor, spices for more overall flavor (especially coriander and paprika), cayenne for heat, coconut sugar for sweetness, apple cider vinegar for acidity, or salt for saltiness. Set aside.",
		"Once the lentils have cooked, drain off any excess liquid and then add spice mixture and parsley or cilantro and mix well to combine (see photo).",
		"Enjoy immediately with salads, rice (or cauliflower rice), bowls, and more. Store leftovers in the refrigerator up to 4-5 days or in the freezer up to 1 month.",
	],
	servings: 6,
	url: "https://minimalistbaker.com/saucy-moroccan-spiced-lentils/",
};

export default recipe;