# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: akbrauer
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: recipe-archive
# "service" is the name of this project. This will also be added to your AWS resource names.
service: db-api

build:
  esbuild:
    external:
      - sharp

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    # Removed quotations from all pg vars
    PGHOST: ${env:PGHOST}
    PGDATABASE: ${env:PGDATABASE}
    PGUSER: ${env:PGUSER}
    PGPASSWORD: ${env:PGPASSWORD}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_KEY: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_SECRET: ${env:CLOUDINARY_SECRET}
  httpApi:
    cors: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    timeout: 20
    package:
      patterns:
        - 'node_modules/sharp'
        - 'node_modules/@img'