const recipes = [
	{
		ingredientid: "678faa83eb0ee52686998935",
		name: "Saucy Moroccan-Spiced Lentils",
		image: "https://minimalistbaker.com/wp-content/uploads/2017/11/Moroccan-Lentils-SQUARE.jpg",
		ingredients: [
			{
				amount: "2",
				unit: "cups",
				name: "water",
				notes: "",
				converted: { amount: "480", unit: "ml" },
				ingredientid: "678faa83eb0ee52686998936",
			},
			{
				amount: "1",
				unit: "cup",
				name: "green lentils",
				notes: "(rinsed and well drained // or sub canned lentils lightly rinsed and well drained)",
				converted: { amount: "192", unit: "g" },
				ingredientid: "678faa83eb0ee52686998937",
			},
			{
				amount: "3",
				unit: "cloves",
				name: "garlic*",
				notes: "(skins removed)",
				converted: { amount: "9", unit: "g" },
				ingredientid: "678faa83eb0ee52686998938",
			},
			{
				amount: "1/2",
				unit: "medium",
				name: "onion",
				notes: "(or 2 small shallots // chopped)",
				converted: { amount: "55", unit: "g" },
				ingredientid: "678faa83eb0ee52686998939",
			},
			{
				amount: "1",
				unit: "large",
				name: "red bell pepper",
				notes: "(or use 2 small), seeds removed, roughly chopped",
				converted: { amount: "150", unit: "g" },
				ingredientid: "678faa83eb0ee5268699893a",
			},
			{
				amount: "2",
				unit: "Tbsp",
				name: "tomato paste",
				notes: "",
				converted: { amount: "30", unit: "g" },
				ingredientid: "678faa83eb0ee5268699893b",
			},
			{
				amount: "1 1/2",
				unit: "Tbsp",
				name: "coconut sugar or maple syrup",
				notes: "(or stevia to taste)",
				converted: { amount: "18", unit: "g" },
				ingredientid: "678faa83eb0ee5268699893c",
			},
			{
				amount: "1/2",
				unit: "tsp",
				name: "sea salt",
				notes: "(plus more to taste)",
				converted: { amount: "1/2", unit: "tsp" },
				ingredientid: "678faa83eb0ee5268699893d",
			},
			{
				amount: "1",
				unit: "Tbsp",
				name: "smoked or sweet paprika",
				notes: "(plus more to taste)",
				converted: { amount: "7", unit: "g" },
				ingredientid: "678faa83eb0ee5268699893e",
			},
			{
				amount: "1",
				unit: "tsp",
				name: "ground cumin",
				notes: "(plus more to taste)",
				converted: { amount: "1", unit: "tsp" },
				ingredientid: "678faa83eb0ee5268699893f",
			},
			{
				amount: "1/2",
				unit: "tsp",
				name: "ground coriander",
				notes: "(plus more to taste)",
				converted: { amount: "1/2", unit: "tsp" },
				ingredientid: "678faa83eb0ee52686998940",
			},
			{
				amount: "1",
				unit: "tsp",
				name: "ground ginger",
				notes: "(plus more to taste)",
				converted: { amount: "1", unit: "tsp" },
				ingredientid: "678faa83eb0ee52686998941",
			},
			{
				amount: "1/2",
				unit: "tsp",
				name: "ground turmeric",
				notes: "(plus more to taste)",
				converted: { amount: "1/2", unit: "tsp" },
				ingredientid: "678faa83eb0ee52686998942",
			},
			{
				amount: "1/2",
				unit: "tsp",
				name: "cayenne pepper",
				notes: "(more or less to preferred spice level)",
				converted: { amount: "1/2", unit: "tsp" },
				ingredientid: "678faa83eb0ee52686998943",
			},
			{
				amount: "1 1/2",
				unit: "Tbsp",
				name: "apple cingredientider vinegar",
				notes: "(or lemon juice)",
				converted: { amount: "22", unit: "ml" },
				ingredientid: "678faa83eb0ee52686998944",
			},
			{
				amount: "3/4",
				unit: "cup",
				name: "fresh chopped parsley or cilantro",
				notes: "(I used 1/2 cilantro + 1/2 parsley)",
				converted: { amount: "~22", unit: "g" },
				ingredientid: "678faa83eb0ee52686998945",
			},
		],
		instructions: [
			"Cook lentils first by bringing water to a boil and adding lentils. Bring back to a boil. Then reduce heat to low and simmer (uncovered) for about 20 minutes or until lentils are tender.",
			"In the meantime, to a food processor or small blender, add garlic*, onion or shallot*, bell pepper, tomato paste, coconut sugar, sea salt, paprika, cumin, coriander, ginger, turmeric, cayenne pepper, and apple cingredientider vinegar. Mix to thoroughly combine.",
			"Taste and adjust flavor as needed, adding more tomato paste for depth of flavor, spices for more overall flavor (especially coriander and paprika), cayenne for heat, coconut sugar for sweetness, apple cingredientider vinegar for acingredientidity, or salt for saltiness. Set asingredientide.",
			"Once the lentils have cooked, drain off any excess liquingredientid and then add spice mixture and parsley or cilantro and mix well to combine (see photo).",
			"Enjoy immediately with salads, rice (or cauliflower rice), bowls, and more. Store leftovers in the refrigerator up to 4-5 days or in the freezer up to 1 month.",
		],
		servings: 6,
		url: "https://minimalistbaker.com/saucy-moroccan-spiced-lentils/",
	},
	{
		ingredientid: "123456789",
		name: "Crack Sauce Recipe (AKA The Best Tahini Dressing!)",
		image: "https://theconscientiouseater.com/wp-content/uploads/Crack-sauce-the-conscientious-eater.png",
		ingredients: [
			{
				ingredientid: "111111111",
				amount: "1/2",
				unit: "cup",
				name: "tahini",
				notes: "",
				converted: {
					amount: "120",
					unit: "g",
				},
			},
			{
				ingredientid: "22222222",
				amount: "2",
				unit: "tablespoons",
				name: "reduced sodium soy sauce",
				notes: "",
				converted: {
					amount: "2",
					unit: "tablespoons",
				},
			},
			{
				ingredientid: "33333333",
				amount: "2",
				unit: "tablespoons",
				name: "rice vinegar",
				notes: "",
				converted: {
					amount: "2",
					unit: "tablespoons",
				},
			},
			{
				ingredientid: "44444444",
				amount: "1",
				unit: "tablespoon",
				name: "maple syrup",
				notes: "",
				converted: {
					amount: "1",
					unit: "tablespoon",
				},
			},
			{
				ingredientid: "55555555",
				amount: "1",
				unit: "teaspoon",
				name: "sesame oil",
				notes: "",
				converted: {
					amount: "1",
					unit: "teaspoon",
				},
			},
			{
				ingredientid: "66666666",
				amount: "1",
				unit: "clove",
				name: "garlic",
				notes: "minced",
				converted: {
					amount: "1",
					unit: "clove",
				},
			},
			{
				ingredientid: "77777777",
				amount: "1",
				unit: "teaspoon",
				name: "grated ginger",
				notes: "",
				converted: {
					amount: "1",
					unit: "teaspoon",
				},
			},
			{
				ingredientid: "888888888",
				amount: "",
				unit: "",
				name: "Water to thin",
				notes: "",
				converted: {
					amount: "",
					unit: "",
				},
			},
		],
		instructions: [
			"Add all of the ingredients (except for the water) to a glass jar and stir until combined.",
			"Add water to thin until the sauce reaches your desired consistency.",
			"Seal the jar and store the sauce in the fringredientidge for up to a week.",
		],
		servings: 6,
		url: "https://theconscientiouseater.com/crack-sauce-recipe-aka-the-best-tahini-dressing/",
	},
	{
		ingredientid: "34",
		name: "Baked Jamaican Jerk Chicken",
		image: "https://i0.wp.com/www.sweetandsorrel.com/wp-content/uploads/2020/03/BakedJerkChicken-4-scaled.jpg?fit=1707%2C2560&ssl=1",
		ingredients: [
			{
				ingredientid: "123",
				amount: "3-4",
				unit: "",
				name: "Scotch bonnet or habanero peppers",
				notes: "remove seeds for less spice",
			},
			{
				ingredientid: "234",
				amount: "5",
				unit: "",
				name: "scallion (green onion) stalks, chopped",
				notes: "",
			},
			{
				ingredientid: "345",
				amount: "1/4",
				unit: "cup",
				name: "fresh thyme, stems included",
				notes: "",
			},
			{
				ingredientid: "456",
				amount: "10",
				unit: "seeds",
				name: "all spice (pimento), dried",
				notes: "",
			},
			{
				ingredientid: "567",
				amount: "1",
				unit: "tbsp",
				name: "fresh grated ginger",
				notes: "",
			},
			{
				ingredientid: "678",
				amount: "4",
				unit: "cloves",
				name: "garlic",
				notes: "",
			},
			{
				ingredientid: "789",
				amount: "2",
				unit: "tbsp",
				name: "brown sugar",
				notes: "",
			},
			{
				ingredientid: "890",
				amount: "1",
				unit: "tsp",
				name: "browning",
				notes: "",
			},
			{
				ingredientid: "901",
				amount: "1",
				unit: "tbsp",
				name: "apple cider vinegar",
				notes: "",
			},
			{
				ingredientid: "012",
				amount: "1/4",
				unit: "cup",
				name: "cooking oil",
				notes: "",
			},
			{
				ingredientid: "34",
				amount: "1",
				unit: "tbsp",
				name: "lime juice",
				notes: "",
			},
			{
				ingredientid: "45",
				amount: "",
				unit: "",
				name: "coarse salt and pepper, to taste",
				notes: "",
			},
			{
				ingredientid: "46",
				amount: "5",
				unit: "",
				name: "scallion (green onion) stalks, chopped",
				notes: "",
			},
			{
				ingredientid: "47",
				amount: "3",
				unit: "stalks",
				name: "celery, chopped",
				notes: "",
			},
			{
				ingredientid: "47",
				amount: "1/2",
				unit: "cup",
				name: "cilantro, stems included",
				notes: "",
			},
			{
				ingredientid: "48",
				amount: "1/4",
				unit: "cup",
				name: "fresh thyme",
				notes: "",
			},
			{
				ingredientid: "49",
				amount: "1",
				unit: "small",
				name: "cooking tomato",
				notes: "",
			},
			{
				ingredientid: "50",
				amount: "4",
				unit: "cloves",
				name: "garlic cloves",
				notes: "",
			},
			{
				ingredientid: "51",
				amount: "5",
				unit: "",
				name: "all spice (pimento) seeds, dried",
				notes: "",
			},
			{
				ingredientid: "52",
				amount: "1",
				unit: "medium",
				name: "green bell pepper",
				notes: "",
			},
			{
				ingredientid: "53",
				amount: "1",
				unit: "",
				name: "scotch bonnet pepper, seeds removed",
				notes: "",
			},
			{
				ingredientid: "54",
				amount: "4-6",
				unit: "",
				name: "chicken quarters (leg + thigh)",
				notes: "",
			},
			{
				ingredientid: "55",
				amount: "1",
				unit: "tbsp",
				name: "Adobo seasoning",
				notes: "",
			},
			{
				ingredientid: "56",
				amount: "2",
				unit: "tbsp",
				name: "browning",
				notes: "",
			},
			{
				ingredientid: "57",
				amount: "1",
				unit: "tbsp",
				name: "habanero sauce",
				notes: "optional",
			},
		],
		instructions: [
			"Prepare the seasonings.\nFirst, make the wet jerk marinade by combining all the ingredients for the marinade in a food processor and pulsing until combined. Set aside.\nNext, make the green seasoning by combining all the ingredients for the marinade in a food processor and pulsing until mixture forms a thick paste. Set aside. [NOTE: You'll have more green seasoning that you need for this recipe. Store any extra seasoning in the fridge, it will keep for about a week].",
			"Prepare chicken by washing with lemon juice and removing excess skin. Season with adobo, habanero sauce (if you want extra spice), browning (for color), wet jerk marinade, and about 3 tbsp of wet green marinade. Use hands to ensure marinade and seasonings are evenly distributed throughout the chicken. Refrigerate for at least 1 hour, ideally overnight.",
			"Preheat oven to 475 degrees. Remove chicken from fridge and bring to room temperature. Bake chicken for 30-35 minutes on each side in a cast iron pan until skin is caramelized and chicken is fully cooked.",
			"Serve with additional wet marinade on top, if desired.",
		],
		servings: 8,
		url: "https://www.sweetandsorrel.com/baked-jerk-chicken/",
	},
];

export default recipes;
